### ISSUE TITLE
Exception Unknow Encoding error

### ISSUE THREAD

**Issue by whiteangel123** [xuzhengyi1995/Renta_Downloader#19]
This is not working anymore, I keep getting "Exception Unknow Encoding" error message in the command window

**Comment by caomeijiangmei** [comment]
Same here, sobs.
@nutritionalyeest Need help~

**Comment by nutritionalyeest** [comment]
@whiteangel123 I've found that error can occur if your cookie has expired, or if it's typed in in wrong. also make sure you have this bit of code after your cookie: ``` .encode('utf-8') ```
(so your main.py line 16 should look like this, except where you insert the cookie text string ofc: )
![image](https://github.com/xuzhengyi1995/Renta_Downloader/assets/80856759/e8e83c95-8bab-4cdc-a74b-9068e31a1113)


@caomeijiangmei I think it may be broken for you because the changes I had you make before are no longer needed. I recommend changing the code in main.py back to how it is in this repo. That's what worked for me! 

Hope this helps!

**Comment by whiteangel123** [comment]
@nutritionalyeest Maybe I'm entering the wrong cookie or wrong URL because this is the traceback error that I got:

`Traceback (most recent call last):
  File "F:\Renta_Downloader-master\main.py", line 308, in <module>
    start_download(url)
  File "F:\Renta_Downloader-master\main.py", line 98, in start_download
    download_info = get_download_info(url)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Renta_Downloader-master\main.py", line 131, in get_download_info
    raise Exception('Unknow encoding.')
Exception: Unknow encoding.`

The format seems to have changed since so maybe I clicked on the wrong item and it's showing me the wrong URL/cookie??

**Comment by caomeijiangmei** [comment]
> @whiteangel123 I've found that error can occur if your cookie has expired, or if it's typed in in wrong. also make sure you have this bit of code after your cookie: `.encode('utf-8')` (so your main.py line 16 should look like this, except where you insert the cookie text string ofc: ) ![image](https://private-user-images.githubusercontent.com/80856759/337450522-e8e83c95-8bab-4cdc-a74b-9068e31a1113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjU0MTIsIm5iZiI6MTcxNzc2NTExMiwicGF0aCI6Ii84MDg1Njc1OS8zMzc0NTA1MjItZThlODNjOTUtOGJhYi00Y2RjLWE3NGItOTA2OGUzMWExMTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEyNTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YTU4N2JlYjY3YjIyMDc4MTE2YTY4MmQ3MGI5NmRhYmIzYWM1MjM1N2UwOWU5NWM5MTgwNDU0MzQ1ZThlMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZtIWQXlFH8UkU0f6tHoiDkz1b1ixULFtAHAiFafVQtU)
> 
> @caomeijiangmei I think it may be broken for you because the changes I had you make before are no longer needed. I recommend changing the code in main.py back to how it is in this repo. That's what worked for me!
> 
> Hope this helps!

It works!! Thx~
When you're typing the manga URL, just remember to add /index.view?ver=new instead of /index.view,
and keep in mind to set your cookie to Medusa_set_version=new.

**Comment by nutritionalyeest** [comment]
> @nutritionalyeest Maybe I'm entering the wrong cookie or wrong URL because this is the traceback error that I got:
> 
> `Traceback (most recent call last): File "F:\Renta_Downloader-master\main.py", line 308, in <module> start_download(url) File "F:\Renta_Downloader-master\main.py", line 98, in start_download download_info = get_download_info(url) ^^^^^^^^^^^^^^^^^^^^^^ File "F:\Renta_Downloader-master\main.py", line 131, in get_download_info raise Exception('Unknow encoding.') Exception: Unknow encoding.`
> 
> The format seems to have changed since so maybe I clicked on the wrong item and it's showing me the wrong URL/cookie??

@whiteangel123  For me, the url that works is the one from the viewer window, it looks like this: 
![image](https://github.com/xuzhengyi1995/Renta_Downloader/assets/80856759/c7ffb26b-6b54-4f99-9f6e-b60d4301da1b)

The cookie is in the developer tools Network tab, index.view:
![image](https://github.com/xuzhengyi1995/Renta_Downloader/assets/80856759/a4924960-7f7e-43e4-a3f5-0aae61ebdff4)

Sorry if this wasn't what you were asking!

**Comment by whiteangel123** [comment]
I now have a different error:

`File "F:\Renta_Downloader-master\main.py", line 159, in get_download_info
    sum_page = int(re_max_page.findall(data)[0])
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Renta_Downloader-master\main.py", line 308, in <module>
    start_download(url)
  File "F:\Renta_Downloader-master\main.py", line 98, in start_download
    download_info = get_download_info(url)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Renta_Downloader-master\main.py", line 161, in get_download_info
    raise Exception('Can not find sum_page on the page')
Exception: Can not find sum_page on the page`

**Comment by caomeijiangmei** [comment]
> I now have a different error:
> 
> `File "F:\Renta_Downloader-master\main.py", line 159, in get_download_info sum_page = int(re_max_page.findall(data)[0]) ~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "F:\Renta_Downloader-master\main.py", line 308, in start_download(url) File "F:\Renta_Downloader-master\main.py", line 98, in start_download download_info = get_download_info(url) ^^^^^^^^^^^^^^^^^^^^^^ File "F:\Renta_Downloader-master\main.py", line 161, in get_download_info raise Exception('Can not find sum_page on the page') Exception: Can not find sum_page on the page`

Same here. Need ur help.Thx!!@nutritionalyeest
